export const loginConst = {
  USER_LOGIN_SUCCES: 'USER_LOGIN_SUCCES',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
}
export const signupConst = {
  USER_SIGNUP_SUCCES: 'USER_SIGNUP_SUCCES',
  USER_SIGNUP_ERROR: 'USER_SIGNUP_ERROR',
}
export const registerConst = {
  USER_REGISTER_SUCCES: 'USER_REGISTER_SUCCES',
  USER_REGISTER_ERROR: 'USER_REGISTER_ERROR',
}
export const Edit_user={
  EDIT_USER :'EDIT_USER_SUCCES',
  EDIT_USERERR: 'EDIT_USER_ERROR',
}

export const Create_User_work = {
  USER_WORKLOG_CREATE_SUCCES: 'USER_WORKLOG_CREATE_SUCCES',
  USER_WORKLOG_CREATE_ERROR: 'USER_WORKLOG_CREATE_ERROR',
}
export const Edit_userlog={
  EDIT_USER_LOG :'EDIT_USER_LOG_SUCCES',
  EDIT_USERERR_LOG: 'EDIT_USER_LOG_ERROR',
}